version: "3.9"
services:
  api:
    build: .
    container_name: hermes_api
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    container_name: hermes_redis
    ports:
      - "6379:6379"

